### ISSUE TITLE
database server connection issue retrieving sequences

### ISSUE THREAD

**Issue by ml31k** [seqcode/chexmix#4]
Hello, 
Running into some issues where the program seems to be accessing a web resource/database (?) for retrieving sequences. I'm running on my cluster where the job nodes do not have external network access, but I also don't see any indication as to why it requires web access.

Thanks!
M

Command used to run (all args point to local files):
module load java/11; module load meme/4.12.0; java -Xmx36G -jar ~/mdwilson/external/ChExMix/v0.5.1/chexmix_v0.51.jar --out CEBPA --threads 16 --geninfo mmus.geninfo --seq /home/mliang/mdwilson/genomes/mmus/Mus_musculus.GRCm38.68.dna.chromosomes.fa --memepath /hpf/tools/centos6/meme/4.12.0/bin/meme --back mmus.back --design CEBPA.design --round 5 --minfold 2  --exclude mmus.exclude

Error log below:
```
Excluding 165 regions from mmus.exclude
Processing HitLoaders for:	CEBPA	1
Processing HitLoaders for:	CEBPA	2
Processing HitLoaders for:	CEBPA	3
Processing HitLoaders for:	CEBPA	DEFAULT
Processing HitLoaders for:	CEBPA	DEFAULT
Loading data from CEBPA:1:signal	Loaded.
Loading data from CEBPA:2:signal	Loaded.
Loading data from CEBPA:3:signal	Loaded.
Loading data from CEBPA:DEFAULT:control	Loaded.
Loading data from CEBPA:DEFAULT:control	Loaded.
Calculating scaling factors for condition:	CEBPA	Complete.
Loaded all experiments:
 Condition CEBPA:	#Replicates:	3
	Replicate:	CEBPA:1
		Signal:	20198686.0	Control:	9786137.0	ScalingFactor:	1.642
	Replicate:	CEBPA:2
		Signal:	19633038.0	Control:	9786137.0	ScalingFactor:	1.717
	Replicate:	CEBPA:3
		Signal:	18055053.0	Control:	9786137.0	ScalingFactor:	1.465
	Pooled replicates for condition:	CEBPA
		Signal:	57886777.0	Control:9786137.0	ScalingFactor:4.764
Finding potential binding regions.
PotentialRegionFilter: condition genomic threshold for CEBPA with bin width 50.0 = 10.0
PotentialRegionFilter: replicate genomic threshold for CEBPA:1 with bin width 50.0 = 6.0
PotentialRegionFilter: replicate genomic threshold for CEBPA:2 with bin width 50.0 = 6.0
PotentialRegionFilter: replicate genomic threshold for CEBPA:3 with bin width 50.0 = 6.0
112355 potential regions found. Total length: 1.7005575E7
Initializing mixture model
Caching sequences
Jul 23, 2021 2:17:46 PM org.apache.tomcat.jdbc.pool.ConnectionPool init
SEVERE: Unable to create initial connections of pool.
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:917)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2088)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:307)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:200)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:699)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:633)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:484)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:142)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:115)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:102)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:126)
	at org.seqcode.data.connections.DatabaseConnectionManager.getConnection(DatabaseConnectionManager.java:75)
	at org.seqcode.genome.sequence.SequenceGenerator.cache(SequenceGenerator.java:129)
	at org.seqcode.genome.sequence.SequenceGenerator.execute(SequenceGenerator.java:164)
	at org.seqcode.genome.sequence.SequenceGenerator.setupRegionCache(SequenceGenerator.java:283)
	at org.seqcode.projects.chexmix.motifs.MotifPlatform.<init>(MotifPlatform.java:81)
	at org.seqcode.projects.chexmix.mixturemodel.BindingMixture.<init>(BindingMixture.java:98)
	at org.seqcode.projects.chexmix.ChExMix.runMixtureModel(ChExMix.java:199)
	at org.seqcode.projects.chexmix.ChExMix.main(ChExMix.java:352)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:988)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2251)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2104)
	... 27 more
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 29 more

com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:917)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2088)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:307)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:200)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:699)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:633)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:484)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:142)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:115)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:102)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:126)
	at org.seqcode.data.connections.DatabaseConnectionManager.getConnection(DatabaseConnectionManager.java:75)
	at org.seqcode.genome.sequence.SequenceGenerator.cache(SequenceGenerator.java:129)
	at org.seqcode.genome.sequence.SequenceGenerator.execute(SequenceGenerator.java:164)
	at org.seqcode.genome.sequence.SequenceGenerator.setupRegionCache(SequenceGenerator.java:283)
	at org.seqcode.projects.chexmix.motifs.MotifPlatform.<init>(MotifPlatform.java:81)
	at org.seqcode.projects.chexmix.mixturemodel.BindingMixture.<init>(BindingMixture.java:98)
	at org.seqcode.projects.chexmix.ChExMix.runMixtureModel(ChExMix.java:199)
	at org.seqcode.projects.chexmix.ChExMix.main(ChExMix.java:352)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:988)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2251)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2104)
	... 27 more
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 29 more
Exception in thread "main" org.seqcode.data.connections.DatabaseException: Couldn't get any sequence for chr1:3010271-3010430
	at org.seqcode.genome.sequence.SequenceGenerator.execute(SequenceGenerator.java:207)
	at org.seqcode.genome.sequence.SequenceGenerator.setupRegionCache(SequenceGenerator.java:283)
	at org.seqcode.projects.chexmix.motifs.MotifPlatform.<init>(MotifPlatform.java:81)
	at org.seqcode.projects.chexmix.mixturemodel.BindingMixture.<init>(BindingMixture.java:98)
	at org.seqcode.projects.chexmix.ChExMix.runMixtureModel(ChExMix.java:199)
	at org.seqcode.projects.chexmix.ChExMix.main(ChExMix.java:352)

```

**Comment by nbartonicek** [comment]
I'm experiencing the same issue. Does the tool need any external information, or is this just a memory problem?

**Comment by cmatKhan** [comment]
Bump -- same issue
